name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Cache VitePress build
        uses: actions/cache@v4
        with:
          path: |
            .vitepress/cache
            .vitepress/dist
          key: ${{ runner.os }}-vitepress-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.md', '**/*.vue', '.vitepress/**/*') }}
          restore-keys: |
            ${{ runner.os }}-vitepress-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-vitepress-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload to Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
